### ISSUE TITLE
History bitcoin not show

### ISSUE THREAD

**Issue by ecxotarama** [peatio/peatio#534]
I trying setup an peatio exchange, i trying sended a liitle bitcoin to bitcoin address in peatio, but not show in Deposit History
This is transaction on  blockchain.info
![blockchain](https://cloud.githubusercontent.com/assets/22535993/18980961/f2048cfa-8703-11e6-818f-5c0cbe5461c5.png)

And this is fund in peatio
![exchang](https://cloud.githubusercontent.com/assets/22535993/18980971/15737cc8-8704-11e6-86da-f510eb1ab07b.png)

I need help ?

**Comment by tkembo** [comment]
Try refreshing your page first. If it still doesn't work, then this is probably one of the two reasons:
1. You haven't put in the correct username/password to connect to bitcoind in your currency.yml file
2. Your daemons are not running. Try restarting them.

**Comment by ecxotarama** [comment]
Hello @tkembo 
This is my file config 
+ bitcoind 

```
server=1
daemon=1
#testnet=1
rpcuser=coinexchange
rpcpassword=HeLl0B0nJ0urS4w4d1K4
 rpcport=8332
 walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'
```

+ currencies.yml
```
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 1000
  rpc: http://coinexchange:HeLl0B0nJ0urS4w4d1K4@127.0.0.1:8332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1L3XutZMGqbAncBgS6h1oJSiCHZvH6zWLf
```

And i had restart daemon:
```
bundle exec rake daemons:stop
bundle exec rake daemons:start
```
But it's can't working
