### ISSUE TITLE
New Coin address is not generated

### ISSUE THREAD

**Issue by istiaqiut** [peatio/peatio#712]
Hello,

Do I need to add walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"COIN_NAME_SINGULAR"}'
command again for new coin in bitcoin.conf file?

Thanks

**Comment by scatterp** [comment]
no you would add this in newcoin.conf not bitcoin.conf for example litecoin.conf

**Comment by istiaqiut** [comment]
I am trying to configure ripple
i have created ~/.bitcoin/xrpcoin.conf file and paste the following
```
server=1
daemon=1

# If run on the test network instead of the real bitcoin network

# You must set rpcuser and rpcpassword to secure the JSON-RPC api
# Please make rpcpassword to something secure, `5gKAgrJv8CQr2CGUhjVbBFLSj29HnE6YGXvfykHJzS3k` for example.
# Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
rpcuser=user
rpcpassword=password
rpcport=18332


# Notify when receiving coins
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"ripple"}'

```
I have another configuration file for BTC

```
server=1
daemon=1

# If run on the test network instead of the real bitcoin network
testnet=1

# You must set rpcuser and rpcpassword to secure the JSON-RPC api
# Please make rpcpassword to something secure, `5gKAgrJv8CQr2CGUhjVbBFLSj29HnE6YGXvfykHJzS3k` for example.
# Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
rpcuser=user
rpcpassword=password
rpcport=18332



# Notify when receiving coins
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

```


In my currencies.yml I have added the following
```
id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 10
  inuse: true
  rpc: http://user:password@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      - address: xxxxxxxxxxxxxxxxxxxxxxxxxxxx

id: 3
  key: ripple
  code: xrp
  symbol: "ꭆ"
  coin: true
  quick_withdraw_max: 110
  rpc: http://user:password@127.0.0.1:18332
  blockchain: https://bithomp.com/explorer/#{txid}
  address_url: https://bithomp.com/explorer/#{address}
  assets:
    accounts:
      - address: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```

Only address of BTC is generated but ripple address is not generated
